baseurl         = "https://www.awbruma.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Anthony W Bruma"
  subtitle    = ""

  cover       = "img/blog-cover.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""

  logo = ""
  orgName = ""
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "AWB"
  authorAvatar = "profile-picture.jpg"
  authorLocation = "Buffalo, NY"
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "under construction"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Primary"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Professional"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Photojournal"
  url = "/categories/photojournal/"
  weight = 99

[[menu.main]]
  name = "Podcast"
  url = "https://www.youtube.com/channel/UCGtNt2yB8NlmQKOUcf6ve8g?view_as=subscriber"
  weight = 95

  [[menu.main]]
    name = "Product"
    url = "/categories/product/"
    weight = 90
