backend:
name: git-gateway
branch: master


media_folder: "static/uploads"
public_folder: "uploads"

collections: 
  - name: "posts"
    label: "posts
    folder: "content/post
    create: true
    slug: "{{year}}-{{slug}}"
    fields: 
    - {label: "Title", name: "title", widget: "string"}
    